// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtXJao3qWzIvpKIJYKAgrrGCdaPN_z8V4',
    appId: '1:969132553240:web:fde595e1acab77ae637f6d',
    messagingSenderId: '969132553240',
    projectId: 'meandyou-ac3ec',
    authDomain: 'meandyou-ac3ec.firebaseapp.com',
    databaseURL:
        'https://meandyou-ac3ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'meandyou-ac3ec.appspot.com',
    measurementId: 'G-2ZFJ6NK4BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCQQ_4NH5DLuXmjiswio8cP3HwgHA7gQ8',
    appId: '1:969132553240:android:b7471cb66105bd99637f6d',
    messagingSenderId: '969132553240',
    projectId: 'meandyou-ac3ec',
    databaseURL:
        'https://meandyou-ac3ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'meandyou-ac3ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAyuOdiNBIh16GuYeqhpz7mWFI0lPaa7w',
    appId: '1:969132553240:ios:b02c02be52809802637f6d',
    messagingSenderId: '969132553240',
    projectId: 'meandyou-ac3ec',
    databaseURL:
        'https://meandyou-ac3ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'meandyou-ac3ec.appspot.com',
    iosBundleId: 'com.example.demo222',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAyuOdiNBIh16GuYeqhpz7mWFI0lPaa7w',
    appId: '1:969132553240:ios:2445e07a36136821637f6d',
    messagingSenderId: '969132553240',
    projectId: 'meandyou-ac3ec',
    databaseURL:
        'https://meandyou-ac3ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'meandyou-ac3ec.appspot.com',
    iosBundleId: 'com.example.demo222.RunnerTests',
  );
}
